# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - content-inspector

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Make WebJob executable
        run: chmod +x App_Data/jobs/continuous/queue-worker/run-queue.sh

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Run composer install
        run: composer validate --no-check-publish && composer install \
          --no-interaction \
          --prefer-dist \
          --no-dev \
          --optimize-autoloader \
          --classmap-authoritative \
          --no-progress

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Build Vite assets
        run: npm run build

      - name: Prepare Laravel directory structure
        run: |
          mkdir -p storage/framework/{cache,sessions,views}
          mkdir -p bootstrap/cache

      - name: Laravel optimize
        run: |
          php artisan route:clear
          php artisan view:clear
          php artisan event:clear

          php artisan route:cache
          php artisan view:cache
          php artisan event:cache

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: |
            .
            !node_modules
            !tests
            !.git
            !.github
            !.env
            !.env.*
            !vendor/**/.git
            !storage/logs
            !storage/framework/cache
            !storage/framework/sessions
            !storage/framework/views

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "content-inspector"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4DEF04232B1F4193ADB1746F429230C7 }}
